cdcservice:
  build: ./eventuate-cdc-service
  ports:
    - "8099:8080"
  links:
    - mysqlbinlogpipeline
    - postgrespollingpipeline
    - postgreswalpipeline
    - kafka
    - zookeeper
  environment:
    EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
    SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}

    EVENTUATE_CDC_READER_MYSQLREADER_TYPE: mysql-binlog
    EVENTUATE_CDC_READER_MYSQLREADER_DATASOURCEURL: jdbc:mysql://mysqlbinlogpipeline:3306/eventuate
    EVENTUATE_CDC_READER_MYSQLREADER_DATASOURCEUSERNAME: mysqluser
    EVENTUATE_CDC_READER_MYSQLREADER_DATASOURCEPASSWORD: mysqlpw
    EVENTUATE_CDC_READER_MYSQLREADER_DATASOURCEDRIVERCLASSNAME: com.mysql.jdbc.Driver
    EVENTUATE_CDC_READER_MYSQLREADER_LEADERSHIPLOCKPATH: /eventuatelocal/cdc/leader/pipeline/1
    EVENTUATE_CDC_READER_MYSQLREADER_CDCDBUSERNAME: root
    EVENTUATE_CDC_READER_MYSQLREADER_CDCDBPASSWORD: rootpassword
    EVENTUATE_CDC_READER_MYSQLREADER_READOLDDEBEZIUMDBOFFSETSTORAGETOPIC: "false"
    EVENTUATE_CDC_READER_MYSQLREADER_MYSQLBINLOGCLIENTUNIQUEID: 1234567890
    EVENTUATE_CDC_READER_MYSQLREADER_OFFSETSTOREKEY: MySqlBinlog

    EVENTUATE_CDC_READER_POSTGRESPOLLINGREADER_TYPE: polling
    EVENTUATE_CDC_READER_POSTGRESPOLLINGREADER_DATASOURCEURL: jdbc:postgresql://postgrespollingpipeline/eventuate
    EVENTUATE_CDC_READER_POSTGRESPOLLINGREADER_DATASOURCEUSERNAME: eventuate
    EVENTUATE_CDC_READER_POSTGRESPOLLINGREADER_DATASOURCEPASSWORD: eventuate
    EVENTUATE_CDC_READER_POSTGRESPOLLINGREADER_DATASOURCEDRIVERCLASSNAME: org.postgresql.Driver
    EVENTUATE_CDC_READER_POSTGRESPOLLINGREADER_LEADERSHIPLOCKPATH: /eventuatelocal/cdc/leader/pipeline/2

    EVENTUATE_CDC_READER_POSTGRESWALREADER_TYPE: postgres-wal
    EVENTUATE_CDC_READER_POSTGRESWALREADER_DATASOURCEURL: jdbc:postgresql://postgreswalpipeline/eventuate
    EVENTUATE_CDC_READER_POSTGRESWALREADER_DATASOURCEUSERNAME: eventuate
    EVENTUATE_CDC_READER_POSTGRESWALREADER_DATASOURCEPASSWORD: eventuate
    EVENTUATE_CDC_READER_POSTGRESWALREADER_DATASOURCEDRIVERCLASSNAME: org.postgresql.Driver
    EVENTUATE_CDC_READER_POSTGRESWALREADER_LEADERSHIPLOCKPATH: /eventuatelocal/cdc/leader/pipeline/3

    EVENTUATE_CDC_PIPELINE_1_TYPE: eventuate-local
    EVENTUATE_CDC_PIPELINE_1_READER: MYSQLREADER

    EVENTUATE_CDC_PIPELINE_2_TYPE: eventuate-local
    EVENTUATE_CDC_PIPELINE_2_READER: POSTGRESPOLLINGREADER

    EVENTUATE_CDC_PIPELINE_3_TYPE: eventuate-local
    EVENTUATE_CDC_PIPELINE_3_READER: POSTGRESWALREADER

    EVENTUATE_CDC_PIPELINE_4_TYPE: eventuate-tram
    EVENTUATE_CDC_PIPELINE_4_READER: MYSQLREADER

    EVENTUATE_CDC_PIPELINE_5_TYPE: eventuate-tram
    EVENTUATE_CDC_PIPELINE_5_READER: POSTGRESPOLLINGREADER

    EVENTUATE_CDC_PIPELINE_6_TYPE: eventuate-tram
    EVENTUATE_CDC_PIPELINE_6_READER: POSTGRESWALREADER
