global:
  scrape_interval:     3s
  evaluation_interval: 3s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['127.0.0.1:9090']

  - job_name: 'spring-prometheus'
    metrics_path: '/prometheus'
    scrape_interval: 3s
    static_configs:
    - targets: ["cdcservice:8080"]